<a href="https://colab.research.google.com/github/ravikannamma/FDP-resource-person/blob/main/new%20numpy_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
# prompt: NUMPY HISTOGRAM

import numpy as np

# Generate an array from 0 to 4 (exclusive) with default step size 1
arr1 = np.arange(5,1,type=np.uint8)
print(arr1)  # [0 1 2 3 4]



TypeError: arange() got an unexpected keyword argument 'type'

In [17]:
import numpy as np

# Example arrays
a = np.array([1, 2,3])
b = np.array([[10], [20], [30]])

# Shapes of arrays
print("Shape of a:", a.shape)  # (3,)
print("Shape of b:", b.shape)  # (3, 1)

# Broadcasting arrays 'a' and 'b'
c = a + b
print("Result of a + b:")
print(c)
# Broadcasting arrays 'a' and 'b'
c = a - b
print("Result of a + b:")
print(c)


Shape of a: (3,)
Shape of b: (3, 1)
Result of a + b:
[[11 12 13]
 [21 22 23]
 [31 32 33]]
Result of a + b:
[[ -9  -8  -7]
 [-19 -18 -17]
 [-29 -28 -27]]


In [ ]:
swap two number
a=10
b=20
a,b=b,a
print(a,b)


In [25]:
import numpy as np

# Example arrays
a = np.array([1, 2])
b = np.array([[10], [20], [30],[40]])

# Shapes of arrays
print("Shape of a:", a.shape)  # (3,)
print("Shape of b:", b.shape)  # (3, 1)

# Broadcasting arrays 'a' and 'b'
c = a + b
print("Result of a + b:")
print(c)
# Broadcasting arrays 'a' and 'b'
c = a - b
print("Result of a + b:")
print(c)

Shape of a: (2,)
Shape of b: (4, 1)
Result of a + b:
[[11 12]
 [21 22]
 [31 32]
 [41 42]]
Result of a + b:
[[ -9  -8]
 [-19 -18]
 [-29 -28]
 [-39 -38]]


In [12]:
hist
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int64')
print(filedata)
(filedata>50) & (filedata<100)


[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76   8]]


array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True, False]])